pow<-read.csv("household_power_consumption.txt",sep=";")
powselect<-(pow[66637:69516,])
datetime<-paste(powselect$Date,powselect$Time)
datetime<-strptime(datetime,"%d/%m/%Y %H:%M:%S")
powselect<-cbind(datetime,powselect)
png(file="plot3.png")
plot(powselect$datetime,as.numeric(powselect$Sub_metering_1), type="l",ylab="Energy Sub Metering",xlab="")
legend("topright", legend="meter 1")
dev.off()
