pow<-read.csv("household_power_consumption.txt",sep=";")
powselect<-(pow[66637:69516,])
datetime<-paste(powselect$Date,powselect$Time)
datetime<-strptime(datetime,"%d/%m/%Y %H:%M:%S")
powselect<-cbind(datetime,powselect)
png(file="plot4.png")
par(mfrow=c(2,2))    
plot(powselect$datetime,as.numeric(powselect$Global_active_power)/500, type="l",ylab="Global Active Power (killowatts)",xlab="")
plot(powselect$datetime,as.numeric(powselect$Voltage)/7,col="BLACK", type="l",ylab="Voltage",xlab="datetime",ylim=c(125,300))
plot(powselect$datetime,as.numeric(powselect$Sub_metering_1), type="l",ylab="Energy Sub Metering",xlab="")
plot(powselect$datetime,as.numeric(powselect$Global_reactive_power)/400, type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
