pow<-read.csv("household_power_consumption.txt",sep=";")
powselect<-(pow[66637:69516,])
datetime<-paste(powselect$Date,powselect$Time)
datetime<-strptime(datetime,"%d/%m/%Y %H:%M:%S")
powselect<-cbind(datetime,powselect)
png(file="plot3.png")
plot(powselect$datetime,as.numeric(powselect$Sub_metering_1), type="l",ylab="Energy Sub Metering",xlab="",ylim=c(0,35))
lines(powselect$datetime,as.numeric(powselect$Sub_metering_2)/10, type="l",col="RED",ylab="Energy Sub Metering",xlab="")
lines(powselect$datetime,as.numeric(powselect$Sub_metering_3), type="l",col="BLUE",ylab="Energy Sub Metering",xlab="")
legend("topright",lty=1,col=c("BLACK","RED","BLUE"), legend=c("Sub_metering 1", "Sub_metering 2","Sub_metering 3"))
dev.off()
